# Generated by Django 3.2 on 2021-04-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framacapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path_to_file',
            field=models.TextField(default='', max_length=40),
        ),
    ]
