# Generated by Django 3.2 on 2021-04-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framacapp', '0002_file_path_to_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileSection',
        ),
        migrations.DeleteModel(
            name='SectionCategory',
        ),
        migrations.DeleteModel(
            name='SectionStatus',
        ),
        migrations.DeleteModel(
            name='StatusData',
        ),
    ]
