# Generated by Django 3.2 on 2021-04-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framacapp', '0006_alter_file_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=40, null=True)),
                ('description', models.TextField(blank=True, max_length=40, null=True)),
                ('creation_date', models.DateTimeField()),
                ('category', models.TextField(max_length=40)),
                ('status', models.TextField(max_length=40)),
                ('data', models.TextField(max_length=40)),
            ],
        ),
    ]
