# Generated by Django 3.2 on 2021-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framacapp', '0007_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path_to_file',
        ),
        migrations.AddField(
            model_name='section',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framacapp.file'),
        ),
    ]
