# Generated by Django 3.2 on 2021-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framacapp', '0008_auto_20210502_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='goal',
        ),
        migrations.RemoveField(
            model_name='section',
            name='category',
        ),
        migrations.RemoveField(
            model_name='section',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='section',
            name='prover',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
